---
kind: pipeline
type: docker
name: wagtail

platform:
  os: linux
  arch: amd64

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./.cache
- name: backend
  image: python:3.6.4
  environment:
    PIPENV_CACHE_DIR: '/drone/src/.cache'
  commands:
    - pip install --trusted-host pypi.python.org pipenv
    - pipenv install -e .[testing]
    - pipenv run flake8 wagtail
    - pipenv run isort --check-only --diff --recursive wagtail
    #- /bin/bash -e -c "pipenv run jinjalint --parse-only wagtail | grep -v 'welcome_page.html:6:70' | tee /dev/tty | wc -l | grep -q '0'"
    - DATABASE_NAME=wagtail.db pipenv run python -u runtests.py
- name: frontend
  image: node:8.11.3
  commands:
    - npm install --no-save
    - npm run lint:js
    - npm run lint:css
    - npm run test:unit:coverage -- --runInBand
    - npm rebuild node-sass
    - npm run dist

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./.cache
volumes:
  - name: cache
    host:
      path: /tmp/cache


