---
kind: pipeline
type: docker
name: wagtail

platform:
  os: linux
  arch: amd64

steps:
- name: backend
  image: python:3.6.4
  commands:
  - pipenv install -e .[testing]
  - pipenv run flake8 wagtail
