---
kind: pipeline
type: docker
name: wagtail

platform:
  os: linux
  arch: amd64

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ~/.local/
- name: backend
  image: python:3.6.4
  commands:
    - pip install --trusted-host pypi.python.org pipenv
    - pipenv install -e .[testing]
    - pipenv run flake8 wagtail
    - pipenv run isort --check-only --diff --recursive wagtail
    - ls -la ~/.local/
- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ~/.local/
volumes:
  - name: cache
    host:
      path: /tmp/cache
